# Generated by Django 5.2.15 on 2026-06-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materia',
            new_name='Materias',
        ),
    ]
