# Generated by Django 5.2.15 on 2026-06-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0002_rename_materia_materias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materias',
            new_name='Materia',
        ),
    ]
