# Generated by Django 5.2.15 on 2026-06-25 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0003_rename_materias_materia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tutor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
