# Generated by Django 5.2.15 on 2026-06-25 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0005_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='materia_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutores_secundario', to='tutorias.materia'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores_principal', to='tutorias.materia'),
        ),
    ]
