# Generated by Django 5.2.15 on 2026-06-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorias', '0006_tutor_materia_2_alter_tutor_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='contacto',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
